# Generated by Django 2.2.2 on 2019-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0002_auto_20190605_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecapimage',
            name='copy_descricao',
            field=models.TextField(default='Copy descrição aqui', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagecapimage',
            name='headline',
            field=models.CharField(default='Coloque sua Headline aqui', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagecapimage',
            name='imgPosition',
            field=models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='Esquerda', max_length=50),
        ),
    ]
