# Generated by Django 2.2.2 on 2019-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0003_auto_20190605_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecapimage',
            name='copy_descricao',
            field=models.TextField(default='Copy descrição aqui'),
        ),
        migrations.AlterField(
            model_name='pagecapimage',
            name='headline',
            field=models.CharField(default='Coloque sua Headline aqui até 300 caracteres', max_length=300),
        ),
    ]
