# Generated by Django 2.2.2 on 2019-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0006_auto_20190605_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecapimage',
            name='headline',
            field=models.TextField(default='Coloque sua Headline aqui até 300 caracteres'),
        ),
    ]
