# Generated by Django 2.2.2 on 2019-06-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0008_auto_20190605_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecapimage',
            options={},
        ),
        migrations.AddField(
            model_name='pagecapimage',
            name='material',
            field=models.CharField(default='E-book vendas online', max_length=100),
        ),
    ]
