# Generated by Django 2.2.2 on 2019-06-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0009_auto_20190605_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecapimage',
            options={'verbose_name_plural': 'PageCapImages'},
        ),
    ]
