# Generated by Django 2.2.2 on 2019-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0010_auto_20190605_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='idelfridesjorge@alu.ufc.br', max_length=254)),
            ],
        ),
    ]
