# Generated by Django 2.2.2 on 2019-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0011_leadsemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Configuracoao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_midea', models.CharField(choices=[('I', 'Imagem'), ('V', 'Vídeo')], default='Imagem', max_length=20)),
                ('image_position', models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='Esquerda', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Configuracoes',
            },
        ),
        migrations.RemoveField(
            model_name='pagecapimage',
            name='image_position',
        ),
    ]
