# Generated by Django 2.2.2 on 2019-06-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0013_auto_20190610_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoao',
            old_name='image_position',
            new_name='midea_position',
        ),
    ]
