# Generated by Django 2.2.2 on 2019-06-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0014_auto_20190610_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracoao',
            old_name='tipo_midea',
            new_name='tipo_media',
        ),
    ]
