# Generated by Django 2.2.2 on 2019-06-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0015_auto_20190610_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracoao',
            new_name='Configuracao',
        ),
    ]
