# Generated by Django 2.2.2 on 2019-06-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0017_auto_20190613_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='media',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
