# Generated by Django 2.2.2 on 2019-06-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0018_auto_20190613_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecapimage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pagecapimage',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
