# Generated by Django 2.2.2 on 2019-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0019_auto_20190613_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecapimage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
