# Generated by Django 2.2.2 on 2019-06-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0022_auto_20190613_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Medias'},
        ),
        migrations.AlterModelOptions(
            name='pagecapimage',
            options={'verbose_name_plural': 'Material'},
        ),
    ]
