# Generated by Django 2.2.2 on 2019-06-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0023_auto_20190613_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsemail',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
