# Generated by Django 2.2.2 on 2019-06-16 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_page_cap_img', '0025_auto_20190614_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecapimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
