# Generated by Django 2.2.7 on 2022-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page_cap_img', '0027_auto_20220603_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='media_position',
            field=models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita'), ('C', 'Centralizado')], default='Esquerda', max_length=20),
        ),
    ]
